### ISSUE TITLE
Day 01b

### ISSUE THREAD

**Issue by dvreed77** [timvisee/advent-of-code-2021#12]
I'm using AoC this year to learn Rust, so I really appreciate the time you've put into doing this.

I'm already stuck on this though with array_windows, particularly these lines

```rust
.array_windows()
.filter(|[a, _, _, d]| a < d)
```

I'm very confused on how this works. My understanding is that array_windows creates a moving window iterable, and so I'm stumped on the following:

- how is it inferred that the window is 3 elements in length?
- where is the sum performed?
- how is array_windows different from [windows](https://doc.rust-lang.org/std/primitive.slice.html#method.windows)?

I appreciate any help you can offer

**Comment by dvreed77** [comment]
Well, this is a case of rubber-duck debugging if I ever saw one. I realize how this is done now:

For those that are curious:

Window 1 = e0 + e1 + e2
Window 2 = e1 + e2 + e3

Window 2 > Window 1 => (e1 + e2 + e3) > (e0 + e1 + e2) => e3 > e0

I'm still curious how array_windows is different than windows

**Comment by timvisee** [comment]
Exactly!

`(a + b + c) < (b + c + d) == (a < d)`

The window functions achieve the same. For `array_windows` the array size is inferred from the type, rather than specifying it yourself. I assumed this to be slightly faster due to the assumptions the Rust compiler might make. This also allows things like array deconstruction. But, using the regular `windows` would be perfectly fine.

**Comment by dvreed77** [comment]
Thanks @timvisee! Maybe you can help me with windows as well. 

I was able to get this working:

```rust
println!(
    "{}",
    include_str!("../input.txt")
        .lines()
        .map(|n| n.parse().unwrap())
        .collect::<Vec<u16>>()
        .windows(4)
        .filter(|w| &&w[0] < &&w[3])
        .count(),
);
```

but Im struggling to find why I need `&&` on the elements for this work.

**Comment by dvreed77** [comment]
Following a few resources [[1]] [[2]], I found this to work

```rust
println!(
    "{}",
    include_str!("../input.txt")
        .lines()
        .map(|n| n.parse().unwrap())
        .collect::<Vec<u16>>()
        .windows(4)
        .flat_map(<&[u16; 4]>::try_from)
        .filter(|[a, _, _, d]| a < d)
        .count(),
);
```

[1: https://stackoverflow.com/questions/58291604/why-can-i-not-use-a-slice-pattern-to-filter-a-window-iterator][1]
[2: https://stackoverflow.com/questions/43828013/why-is-being-used-in-closure-arguments][2]

[1]: https://stackoverflow.com/questions/58291604/why-can-i-not-use-a-slice-pattern-to-filter-a-window-iterator
[2]: https://stackoverflow.com/questions/43828013/why-is-being-used-in-closure-arguments

**Comment by timvisee** [comment]
That is correct. A slice (a reference, borrowed array, rather than an owned array) doesn't have a known size at compile time. Because of this, you can't destruct, because the compiler can't guarantee you always have 4 items. An array does have a known size at compile time, which is part of the array type definition, which is why destruction with `[a, _, _, d]` is possible.

When using destruction like this I'd recommend to use `array_windows()` rather than `windows()`, because you're doing extra work now with `flat_map()` and `try_from`. If that isn't possible because it requires nightly, you're probably better of using indices on the slice directly like you've done before with `.filter(|w| &&w[0] < &&w[3])`.

The reason why you need to use `&&` is because `w` is a double reference. `windows()` gives a reference, and `filter()` gives another reference. You can probably dereference in the closure like this `.filter(|&w| &w[0] < &w[3])` or even like this `.filter(|&&w| w[0] < w[3])`.

I'm doing this from the top of my head, so excuse me if I made any mistakes.

Also, thanks so much for your donation. I appreciate that a lot! :smile:
