### ISSUE TITLE
Question regarding day 6.

### ISSUE THREAD

**Issue by tk-nguyen** [timvisee/advent-of-code-2021#3]
Hello! I'm reading your solution to day 6, and I can't figure out why did you add 7 when iterating through the days for the index. If you can explain that to me I'd be greatly appreciated!

**Comment by FlakM** [comment]
> each lanternfish creates a new lanternfish once every 7 days

```rust
 (1..256).for_each(|day| map[(day + 7) % 9] += map[day % 9]);
```

So if i understand this correctly the fishes belonging to day 1 should be incremented to day 1 + 7. Jesus this is so elegant. Kudos

**Comment by tk-nguyen** [comment]
Ah yes, I totally ignored that because I thought it was just some flavor text 😅. Thanks!

**Comment by timvisee** [comment]
That's right.

So we have these basic rules:

- the Time To Live of each fish decreases by `1` each day
- when a fish has a TTL of `0` it:
  - respawns with a TTL of 6
  - respawns with a TTL of 8
  - dies

Based on this, the TTL can be 9 different values (`[0, 8]`). This means we can store everything in an array with a length of 9. The array index can be used as TTL value, each value represents the number of fish.

Now with this design, iterating through a day is easy:

```rust
for day in 0..256 {
    let spawn = map[0];

    // Update our TTLs, shift everything one up, TTL 1 becomes TTL 0, TTL 0 is overwritten and dies
    (0..8).for_each(|i| map[i] = map[i + 1]);

    // Respawn TTL 6 and TTL 8
    map[6] += spawn;
    map[8] = spawn;
}
```

Fish at TTL 0 die because their value is dropped when updating the TTLs, it is essentially overwritten with the value from TTL 1. We also manuall respawn fish at TTL 6 and TTL 8. TTL 8 will always be zero after we've shifted, it will therefore become the same as what TTL 0 was, which is why we can use `=` rather than `+=`.

We can simplify this _shifting_ process by [rotating](https://doc.rust-lang.org/std/primitive.slice.html#method.rotate_left) the array. This will shift all the TTL values by one left/up, so we don't have to move each value through the array ourselves anymore. As a bonus, this wraps the first array value around to become the last. In other words, it wraps TTL 0 back to TTL 8. This means we don't have to respawn at TTL 8, and fish at TTL 0 doesn't have to die.

We simplified our rules to:

- when a fish has a TTL of `0` it:
  - respawns with a TTL of 6
  - becomes a TTL of 8

We essentially create new fish every 7 days (6 + 1 because we're zero indexed). The puzzle description hints to this:

> (..) each lanternfish creates a new lanternfish once every 7 days.

Our simplified version looks like this:

```rust
for day in 0..256 {
    let spawn = map[0];

    // Update our TTLs, TTL 1 becomes TTL 0, TTL 0 becomes TTL 8
    map.rotate_left(1);

    // Respawn
    map[6] += spawn;
}
```

Now it's time to optimize further. Rather than rotating/moving all fish through the array each iteration, we can shift our array/TTL index so all fish can stay in place. This can be a little tricky to understand, but lets try and continue.

For example:
- First iteration, day 0:
  - TTL 0 lives at index 0
  - TTL 1 lives at index 1
  - ...
  - TTL 7 lives at index 7
  - TTL 8 lives at index 8
- Second iteration, day 1:
  - TTL 0 lives at index 1
  - TTL 1 lives at index 2
  - ...
  - TTL 7 lives at index 8
  - TTL 8 lives at index 0
- _etc_

We can locate the index with a modulo like this to get the above pattern: `(day + ttl) % 9`.

As we've simplified earlier, TTL 0 becomes TTL 8 because it wraps, we only have to respawn new fish at TTL 6. We can optimize our code to:

```rust
for day in 0..256 {
    // Respawn TTL 0 at TTL 6 (+1 for shifting)
    map[(day + 7) % 9] += map[day % 9];
}
```

Note that we respawn at TTL `7 = 6 + 1` here. This is because the fish is respawned before _shifting_, after _shifting_ it will be TTL 6.

The above can then be shortened to this, which is what I ended up [with](https://github.com/timvisee/advent-of-code-2021/blob/5b99a4aed627b393ad6a27b496d513ccfac941ad/day06b/src/main.rs#L9):

```rust
(1..256).for_each(|day| map[(day + 7) % 9] += map[day % 9]);
```

Quite elegant.

I hope this explains how I got here! Good luck with the upcoming days. :smile:

**Comment by tk-nguyen** [comment]
Thank you!
