### ISSUE TITLE
Day08 Part B runs into unreachable code macro

### ISSUE THREAD

**Issue by KnutKnusper** [timvisee/advent-of-code-2021#5]
The current code runs into the unreachable code macro.
![2021-12-10 12_46_25-main rs - day08b - Visual Studio Code](https://user-images.githubusercontent.com/55513589/145574142-b0c3b40b-a9dd-4652-9c0a-e096a60a5cf2.png)

I'm not sure why, but I think the &[u8] array was not split at this`.split(|&b| b == b' ')` command.

**Comment by timvisee** [comment]
That's weird! I assume this is for your own input.

I imagine this can happen because of one or two things:

- your input file has a newline at the end (most editors add it when saving)
- your input file uses CRLF (`\r\n`) (default on Windows) as newline separator, rather than LF (`\n`)

To remove a suffixed newline you may use `truncate -s -1 input.txt` on Linux. Though I don't know the equivalent on Windows. You could invoke the command through WSL on the input file.

To change CRLF to LF you'll likely be able to change the newline style in your editor. Change it to LF or Unix.

Note that I try to optimize these solutions for speed. I therefore don't clean up the input (with things like `trim`). And when using binary arrays, I just split on `\n` rather than supporting both.

**Comment by KnutKnusper** [comment]
No, I tried the input file from your repository without changing it.  

But you are right, if I change your input file to LF `'\n'` it works.

Thanks

**Comment by timvisee** [comment]
Thanks for letting me know! Now that I think of it, `git` could also have translated the newlines while checking out.

Maybe I should just support both line endings, along with a suffixed newline.
