### ISSUE TITLE
Intuition behind Day 3 Part 1

### ISSUE THREAD

**Issue by alexkolson** [timvisee/advent-of-code-2021#6]
Hey there Tim,

First of all, thank you very much for working on this year's advent of code in the open in Rust, it's really helping me learn. 

I'm having quite a hard time grasping the intuition behind the bit-shifting going on in the first part of the day 3 solution. I understand that at a high level, a left bit shift multiplies by two and a right bit shift divides by two. What I don't understand is for example on [line 12](https://github.com/timvisee/advent-of-code-2021/blob/master/day03a/src/main.rs#L12) where `bits` is `AND`ed with 1, shifted to the left `i`, then immediately shifted to the right by `i`, and finally added to the count.

[Line 17](https://github.com/timvisee/advent-of-code-2021/blob/master/day03a/src/main.rs#L17) is also hard for me to understand and would love some explanation there as well.

Perhaps if you (or anybody else for that matter) has a spare moment and could help me understand what is going on that would be awesome!

I appreciate your work very much!

**Comment by inflation** [comment]
Note that in Rust, `>>` takes precedence over `&`. So line 12 extracts the `i`th bit and check if it's one and add them up. Line 17 is the same logic.

**Comment by timvisee** [comment]
For day 3 part 1 we need to get the most common bits in a set of bit strings.

The [`fold`](https://github.com/timvisee/advent-of-code-2021/blob/7ef244bd336b1707b04ea2056874d37012805b95/day03a/src/main.rs#L8-L14) creates a shared vector with 12 items, one for each bit position. Each item is a count of how many times a `1` occurs in that specific position. The fold [body](https://github.com/timvisee/advent-of-code-2021/blob/7ef244bd336b1707b04ea2056874d37012805b95/day03a/src/main.rs#L9-L13) takes this bit count vector, and updates it for the current bit string (`bits`), increasing the count for each `1`.

https://github.com/timvisee/advent-of-code-2021/blob/7ef244bd336b1707b04ea2056874d37012805b95/day03a/src/main.rs#L12

This line essentially counts. `n` is the currently accumulated value. `((bits & 1 << i) >> i)` is `1` if the current bit is `1`, it is `0` if the current bit is `0`. This increases the count by one if a `1` is seen at position `i`. Note that I count from the right here, rather than from the left, which is typical when working with bits.

`1 << i` is used to create a mask for the current bit position. For example, for bit position 2, this mask is `0b00000100`. The `bits & mask` operation is used to determine whether the current bit is `1` or `0`. If it is `1`, the mask is kept, if it is `0`, the mask becomes zero (`0b00000000`). We'd like to increment the accumulator `n` by `1` if the mask is kept. We can't simply add the mask value because the value is 1, 2, 4 or more depending on what bit we're currently masking. To resolve this, I do a final shift back with `result >> i` to transform our mask result to a value of 1 or 0. This is finally added to the accumulator to count the `1` bits. This can be done with an if-statement for example, but this approach is much shorter and removes branching.

So to go over it one more time. We count the `1` bits at each position. `((bits & 1 << i) >> i)` is `1` if the bit at that position is `1`, it is `0` if it is `0`, summing them together.

https://github.com/timvisee/advent-of-code-2021/blob/7ef244bd336b1707b04ea2056874d37012805b95/day03a/src/main.rs#L17

With this line I build `gamma`. It checks whether the `1` or `0` bit was most common. It takes the bit counts for each position and builds the final `gamma` bit string.

`(b >= COUNT / 2)` is used on each bit position. It is `true` if the most common bit in that position is `1` (determined with count `b` and the number of inputs), it is `false` if `0` is the most common.

The `as u32` is used as hack to convert the boolean into a `1` or `0`. So `(b >= COUNT / 2) as u32` is `1` if the most common bit is `1`, it is `0` otherwise. The `<< i` is used to shift the 1 or 0 to the current bit position.

Imagine having bit strings with 4 positions. Where `1` is the most common for the first, third and fourth position. In that case this map would produce:

- `0b1000`
- `0b0000`
- `0b0010`
- `0b0001`

The final [`sum`](https://github.com/timvisee/advent-of-code-2021/blob/7ef244bd336b1707b04ea2056874d37012805b95/day03a/src/main.rs#L18) merges this into `0b1011`.

---

So. This can be a bit tricky to understand. But, I've done it this way to make it short, fast, and to remove branching.

I hope going through it like this makes it clear what I'm doing here!

Also, thanks so much for your donation. That is very much appreciated! :smile:

**Comment by alexkolson** [comment]
Hey @timvisee thanks for the explanation! I will have to re-read it a few times but it's exactly what I needed. Thank you!

**Comment by timvisee** [comment]
Yeah. I find it hard to explain things like this through text. Good luck. 

Feel free to ask if something is still unclear.
